apiVersion: v1
kind: Service
metadata:
  name: estore-app
  labels:
    app: estore-app
spec:
  selector:
    app: estore-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: estore-app
  labels:
    app: estore-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estore-app
  template:
    metadata:
      labels:
        app: estore-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: 647240904064.dkr.ecr.us-east-1.amazonaws.com/estore_service_registry:v1
        imagePullPolicy: Always
        envFrom:
            - configMapRef:
                name: postgres-db-config
        ports:
        - containerPort: 8080